package demo.code.phone;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

// Generated by Spring Initializr

// Verifies in test form that all the dependency injection is working correctly.
// Doesn't matter in a simple project like this...  but it's a
// good starting point for integration testing in a more complex project.
@SpringBootTest
class PhoneApplicationTests {

	@Test
	void contextLoads() {
	}

}
